/**
 * Declaration merging with the global `Env` interface generated by
 * `npm run cf-typegen` in worker-configuration.d.ts (that file is
 * generated and never hand-edited — see docs/project-rules.md,
 * "Generated files"). These two Secrets are registered later via
 * `wrangler secret put`, so they never appear in wrangler.jsonc `vars`
 * and `wrangler types` has no way to generate a type for them yet.
 *
 * Declared optional because they are not guaranteed to be set (neither
 * is registered as of Phase 3) — callers must handle the missing case
 * safely rather than assume presence. See docs/security-and-privacy.md
 * ("Secret management").
 */
interface Env {
  TELEGRAM_WEBHOOK_SECRET?: string;
  TELEGRAM_BOT_TOKEN?: string;
}
