/**
 * Declaration merging with the global `Env` interface generated by
 * `npm run cf-typegen` in worker-configuration.d.ts (that file is
 * generated and never hand-edited — see docs/project-rules.md,
 * "Generated files"). These Secrets are registered later via
 * `wrangler secret put`, so they never appear in wrangler.jsonc `vars`
 * and `wrangler types` has no way to generate a type for them yet.
 *
 * Declared optional because they are not guaranteed to be set (none are
 * registered as of Phase 4) — callers must handle the missing case
 * safely rather than assume presence. See docs/security-and-privacy.md
 * ("Secret management"). Only the Secret name is declared here — never
 * a value.
 */
interface Env {
  TELEGRAM_WEBHOOK_SECRET?: string;
  TELEGRAM_BOT_TOKEN?: string;
  OPENAI_API_KEY?: string;
  /** Phase 8A: authenticates `POST /admin/bootstrap` — see src/handlers/admin-bootstrap.ts. */
  SETUP_ADMIN_SECRET?: string;
}
